version: '3.8'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: app1
    networks:
      - laravel_network

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: app2
    networks:
      - laravel_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8001:81"
      - "8002:82"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
